
trigger:
- master
pr:
- master

jobs:

- job: 'PlatformIO_CI'
  pool:
    vmImage: 'ubuntu-latest'
  container: 'python:2.7'
  strategy:
    matrix:
      Buffer:
        ExampleSrc: 'examples/Buffer/Buffer.ino'
      Parser:
        ExampleSrc: 'examples/Parser/Parser.ino'
      Parser_KeyValue:
        ExampleSrc: 'examples/Parser-KeyValue/Parser-KeyValue.ino'
      Callback:
        ExampleSrc: 'examples/Callback/Callback.ino'
      Callback_P:
        ExampleSrc: 'examples/Callback_P/Callback_P.ino'
      Callback_non_blocking:
        ExampleSrc: 'examples/Callback_non_blocking/Callback_non_blocking.ino'
  steps:
  - script: |
      virtualenv venv

      . venv/bin/activate
      pip install -U PlatformIO==4.0.0
      platformio update
    displayName: 'Install PlatformIO'
  - script: |
      . venv/bin/activate
      platformio ci --lib="." --board=nanoatmega328 --board=esp12e --board=leonardo
    displayName: 'Run a multi-line script'
    env:
      PLATFORMIO_CI_SRC: $(ExampleSrc)
